// Generated by CoffeeScript 1.3.3
(function() {
  var apiInfo, biblia, should;

  should = require('should');

  biblia = require('..');

  apiInfo = require('../key');

  describe('Biblia', function() {
    before(function() {
      return this.client = biblia(apiInfo.key);
    });
    describe('when getting a list of bibles', function() {
      return it('should include kjv', function(done) {
        return this.client.find(function(bibles) {
          var b;
          ((function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = bibles.length; _i < _len; _i++) {
              b = bibles[_i];
              _results.push(b.bible);
            }
            return _results;
          })()).should.includeEql('kjv');
          return done();
        });
      });
    });
    return describe('when looking up John 3:16', function() {
      return it('when using kjv', function(done) {
        return this.client.lookup('kjv', 'John 3:16', function(verse) {
          verse.should.eql('For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.');
          return done();
        });
      });
    });
  });

}).call(this);
