// Generated by CoffeeScript 1.3.3
(function() {
  var BASE_URL, Biblia, request;

  request = require('superagent');

  BASE_URL = "http://api.biblia.com/v1/bible";

  Biblia = function(apiKey) {
    return this.apiKey = apiKey;
  };

  Biblia.prototype.find = function(callback) {
    return request.get("" + BASE_URL + "/find").send({
      key: this.apiKey
    }).end(function(err, res) {
      return callback(JSON.parse(res.text).bibles);
    });
  };

  Biblia.prototype.lookup = function(version, reference, callback) {
    return request.get("" + BASE_URL + "/content/" + version + ".js").send({
      key: this.apiKey
    }).send({
      passage: reference.replace(':', '.')
    }).end(function(err, res) {
      return callback(JSON.parse(res.text).text);
    });
  };

  module.exports = function(apiKey) {
    return new Biblia(apiKey);
  };

}).call(this);
